[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scanner = { path = "../scanner" }
as-any = "0.3.0"

[lib]
path = "src/parser.rs"